// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

    
#include "Motor.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset

extern void Motor_STOP_enter(Motor* sm);
extern void Motor_STOP_exit(Motor* sm);
extern void Motor_STOP_do(Motor* sm);
extern void Motor_LEFT_MOVE_enter(Motor* sm);
extern void Motor_LEFT_MOVE_exit(Motor* sm);
extern void Motor_LEFT_MOVE_do(Motor* sm);
extern void Motor_RIGHT_MOVE_enter(Motor* sm);
extern void Motor_RIGHT_MOVE_exit(Motor* sm);
extern void Motor_RIGHT_MOVE_do(Motor* sm);
extern void Motor_LEFT_MOVE_MAX_enter(Motor* sm);
extern void Motor_LEFT_MOVE_MAX_exit(Motor* sm);
extern void Motor_LEFT_MOVE_MAX_do(Motor* sm);
extern void Motor_RIGHT_MOVE_MAX_enter(Motor* sm);
extern void Motor_RIGHT_MOVE_MAX_exit(Motor* sm);
extern void Motor_RIGHT_MOVE_MAX_do(Motor* sm);



// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(Motor* sm, Motor_StateId desired_state);

static void ROOT_enter(Motor* sm);

static void LEFT_MOVE_enter(Motor* sm);

static void LEFT_MOVE_exit(Motor* sm);

static void LEFT_MOVE_do(Motor* sm);

static void LEFT_MOVE_left_move_max(Motor* sm);

static void LEFT_MOVE_right_move(Motor* sm);

static void LEFT_MOVE_stop(Motor* sm);

static void LEFT_MOVE_MAX_enter(Motor* sm);

static void LEFT_MOVE_MAX_exit(Motor* sm);

static void LEFT_MOVE_MAX_do(Motor* sm);

static void LEFT_MOVE_MAX_right_move(Motor* sm);

static void LEFT_MOVE_MAX_stop(Motor* sm);

static void RIGHT_MOVE_enter(Motor* sm);

static void RIGHT_MOVE_exit(Motor* sm);

static void RIGHT_MOVE_do(Motor* sm);

static void RIGHT_MOVE_left_move(Motor* sm);

static void RIGHT_MOVE_right_move_max(Motor* sm);

static void RIGHT_MOVE_stop(Motor* sm);

static void RIGHT_MOVE_MAX_enter(Motor* sm);

static void RIGHT_MOVE_MAX_exit(Motor* sm);

static void RIGHT_MOVE_MAX_do(Motor* sm);

static void RIGHT_MOVE_MAX_left_move(Motor* sm);

static void RIGHT_MOVE_MAX_stop(Motor* sm);

static void STOP_enter(Motor* sm);

static void STOP_exit(Motor* sm);

static void STOP_do(Motor* sm);

static void STOP_left_move(Motor* sm);

static void STOP_right_move(Motor* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void Motor_ctor(Motor* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void Motor_start(Motor* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(STOP)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `STOP`.
            STOP_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void Motor_dispatch_event(Motor* sm, Motor_EventId event_id)
{
    switch (sm->state_id)
    {
        // STATE: Motor
        case Motor_StateId_ROOT:
            // No events handled by this state (or its ancestors).
            break;
        
        // STATE: LEFT_MOVE
        case Motor_StateId_LEFT_MOVE:
            switch (event_id)
            {
                case Motor_EventId_DO: LEFT_MOVE_do(sm); break;
                case Motor_EventId_RIGHT_MOVE: LEFT_MOVE_right_move(sm); break;
                case Motor_EventId_STOP: LEFT_MOVE_stop(sm); break;
                case Motor_EventId_LEFT_MOVE_MAX: LEFT_MOVE_left_move_max(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: LEFT_MOVE_MAX
        case Motor_StateId_LEFT_MOVE_MAX:
            switch (event_id)
            {
                case Motor_EventId_DO: LEFT_MOVE_MAX_do(sm); break;
                case Motor_EventId_RIGHT_MOVE: LEFT_MOVE_MAX_right_move(sm); break;
                case Motor_EventId_STOP: LEFT_MOVE_MAX_stop(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: RIGHT_MOVE
        case Motor_StateId_RIGHT_MOVE:
            switch (event_id)
            {
                case Motor_EventId_DO: RIGHT_MOVE_do(sm); break;
                case Motor_EventId_LEFT_MOVE: RIGHT_MOVE_left_move(sm); break;
                case Motor_EventId_STOP: RIGHT_MOVE_stop(sm); break;
                case Motor_EventId_RIGHT_MOVE_MAX: RIGHT_MOVE_right_move_max(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: RIGHT_MOVE_MAX
        case Motor_StateId_RIGHT_MOVE_MAX:
            switch (event_id)
            {
                case Motor_EventId_DO: RIGHT_MOVE_MAX_do(sm); break;
                case Motor_EventId_LEFT_MOVE: RIGHT_MOVE_MAX_left_move(sm); break;
                case Motor_EventId_STOP: RIGHT_MOVE_MAX_stop(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: STOP
        case Motor_StateId_STOP:
            switch (event_id)
            {
                case Motor_EventId_DO: STOP_do(sm); break;
                case Motor_EventId_LEFT_MOVE: STOP_left_move(sm); break;
                case Motor_EventId_RIGHT_MOVE: STOP_right_move(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(Motor* sm, Motor_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case Motor_StateId_LEFT_MOVE: LEFT_MOVE_exit(sm); break;
            
            case Motor_StateId_LEFT_MOVE_MAX: LEFT_MOVE_MAX_exit(sm); break;
            
            case Motor_StateId_RIGHT_MOVE: RIGHT_MOVE_exit(sm); break;
            
            case Motor_StateId_RIGHT_MOVE_MAX: RIGHT_MOVE_MAX_exit(sm); break;
            
            case Motor_StateId_STOP: STOP_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(Motor* sm)
{
    sm->state_id = Motor_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state LEFT_MOVE
////////////////////////////////////////////////////////////////////////////////

static void LEFT_MOVE_enter(Motor* sm)
{
    sm->state_id = Motor_StateId_LEFT_MOVE;
    
    // LEFT_MOVE behavior
    // uml: enter / { Motor_LEFT_MOVE_enter(sm); }
    {
        // Step 1: execute action `Motor_LEFT_MOVE_enter(sm);`
        Motor_LEFT_MOVE_enter(sm);
    } // end of behavior for LEFT_MOVE
}

static void LEFT_MOVE_exit(Motor* sm)
{
    // LEFT_MOVE behavior
    // uml: exit / { Motor_LEFT_MOVE_exit(sm); }
    {
        // Step 1: execute action `Motor_LEFT_MOVE_exit(sm);`
        Motor_LEFT_MOVE_exit(sm);
    } // end of behavior for LEFT_MOVE
    
    sm->state_id = Motor_StateId_ROOT;
}

static void LEFT_MOVE_do(Motor* sm)
{
    // LEFT_MOVE behavior
    // uml: do / { Motor_LEFT_MOVE_do(sm); }
    {
        // Step 1: execute action `Motor_LEFT_MOVE_do(sm);`
        Motor_LEFT_MOVE_do(sm);
    } // end of behavior for LEFT_MOVE
    
    // No ancestor handles this event.
}

static void LEFT_MOVE_left_move_max(Motor* sm)
{
    // LEFT_MOVE behavior
    // uml: LEFT_MOVE_MAX TransitionTo(LEFT_MOVE_MAX)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        LEFT_MOVE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `LEFT_MOVE_MAX`.
        LEFT_MOVE_MAX_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for LEFT_MOVE
    
    // No ancestor handles this event.
}

static void LEFT_MOVE_right_move(Motor* sm)
{
    // LEFT_MOVE behavior
    // uml: RIGHT_MOVE TransitionTo(RIGHT_MOVE)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        LEFT_MOVE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `RIGHT_MOVE`.
        RIGHT_MOVE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for LEFT_MOVE
    
    // No ancestor handles this event.
}

static void LEFT_MOVE_stop(Motor* sm)
{
    // LEFT_MOVE behavior
    // uml: STOP TransitionTo(STOP)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        LEFT_MOVE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `STOP`.
        STOP_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for LEFT_MOVE
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state LEFT_MOVE_MAX
////////////////////////////////////////////////////////////////////////////////

static void LEFT_MOVE_MAX_enter(Motor* sm)
{
    sm->state_id = Motor_StateId_LEFT_MOVE_MAX;
    
    // LEFT_MOVE_MAX behavior
    // uml: enter / { Motor_LEFT_MOVE_MAX_enter(sm); }
    {
        // Step 1: execute action `Motor_LEFT_MOVE_MAX_enter(sm);`
        Motor_LEFT_MOVE_MAX_enter(sm);
    } // end of behavior for LEFT_MOVE_MAX
}

static void LEFT_MOVE_MAX_exit(Motor* sm)
{
    // LEFT_MOVE_MAX behavior
    // uml: exit / { Motor_LEFT_MOVE_MAX_exit(sm); }
    {
        // Step 1: execute action `Motor_LEFT_MOVE_MAX_exit(sm);`
        Motor_LEFT_MOVE_MAX_exit(sm);
    } // end of behavior for LEFT_MOVE_MAX
    
    sm->state_id = Motor_StateId_ROOT;
}

static void LEFT_MOVE_MAX_do(Motor* sm)
{
    // LEFT_MOVE_MAX behavior
    // uml: do / { Motor_LEFT_MOVE_MAX_do(sm); }
    {
        // Step 1: execute action `Motor_LEFT_MOVE_MAX_do(sm);`
        Motor_LEFT_MOVE_MAX_do(sm);
    } // end of behavior for LEFT_MOVE_MAX
    
    // No ancestor handles this event.
}

static void LEFT_MOVE_MAX_right_move(Motor* sm)
{
    // LEFT_MOVE_MAX behavior
    // uml: RIGHT_MOVE TransitionTo(RIGHT_MOVE)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        LEFT_MOVE_MAX_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `RIGHT_MOVE`.
        RIGHT_MOVE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for LEFT_MOVE_MAX
    
    // No ancestor handles this event.
}

static void LEFT_MOVE_MAX_stop(Motor* sm)
{
    // LEFT_MOVE_MAX behavior
    // uml: STOP TransitionTo(STOP)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        LEFT_MOVE_MAX_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `STOP`.
        STOP_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for LEFT_MOVE_MAX
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state RIGHT_MOVE
////////////////////////////////////////////////////////////////////////////////

static void RIGHT_MOVE_enter(Motor* sm)
{
    sm->state_id = Motor_StateId_RIGHT_MOVE;
    
    // RIGHT_MOVE behavior
    // uml: enter / { Motor_RIGHT_MOVE_enter(sm); }
    {
        // Step 1: execute action `Motor_RIGHT_MOVE_enter(sm);`
        Motor_RIGHT_MOVE_enter(sm);
    } // end of behavior for RIGHT_MOVE
}

static void RIGHT_MOVE_exit(Motor* sm)
{
    // RIGHT_MOVE behavior
    // uml: exit / { Motor_RIGHT_MOVE_exit(sm); }
    {
        // Step 1: execute action `Motor_RIGHT_MOVE_exit(sm);`
        Motor_RIGHT_MOVE_exit(sm);
    } // end of behavior for RIGHT_MOVE
    
    sm->state_id = Motor_StateId_ROOT;
}

static void RIGHT_MOVE_do(Motor* sm)
{
    // RIGHT_MOVE behavior
    // uml: do / { Motor_RIGHT_MOVE_do(sm); }
    {
        // Step 1: execute action `Motor_RIGHT_MOVE_do(sm);`
        Motor_RIGHT_MOVE_do(sm);
    } // end of behavior for RIGHT_MOVE
    
    // No ancestor handles this event.
}

static void RIGHT_MOVE_left_move(Motor* sm)
{
    // RIGHT_MOVE behavior
    // uml: LEFT_MOVE TransitionTo(LEFT_MOVE)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        RIGHT_MOVE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `LEFT_MOVE`.
        LEFT_MOVE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for RIGHT_MOVE
    
    // No ancestor handles this event.
}

static void RIGHT_MOVE_right_move_max(Motor* sm)
{
    // RIGHT_MOVE behavior
    // uml: RIGHT_MOVE_MAX TransitionTo(RIGHT_MOVE_MAX)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        RIGHT_MOVE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `RIGHT_MOVE_MAX`.
        RIGHT_MOVE_MAX_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for RIGHT_MOVE
    
    // No ancestor handles this event.
}

static void RIGHT_MOVE_stop(Motor* sm)
{
    // RIGHT_MOVE behavior
    // uml: STOP TransitionTo(STOP)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        RIGHT_MOVE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `STOP`.
        STOP_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for RIGHT_MOVE
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state RIGHT_MOVE_MAX
////////////////////////////////////////////////////////////////////////////////

static void RIGHT_MOVE_MAX_enter(Motor* sm)
{
    sm->state_id = Motor_StateId_RIGHT_MOVE_MAX;
    
    // RIGHT_MOVE_MAX behavior
    // uml: enter / { Motor_RIGHT_MOVE_MAX_enter(sm); }
    {
        // Step 1: execute action `Motor_RIGHT_MOVE_MAX_enter(sm);`
        Motor_RIGHT_MOVE_MAX_enter(sm);
    } // end of behavior for RIGHT_MOVE_MAX
}

static void RIGHT_MOVE_MAX_exit(Motor* sm)
{
    // RIGHT_MOVE_MAX behavior
    // uml: exit / { Motor_RIGHT_MOVE_MAX_exit(sm); }
    {
        // Step 1: execute action `Motor_RIGHT_MOVE_MAX_exit(sm);`
        Motor_RIGHT_MOVE_MAX_exit(sm);
    } // end of behavior for RIGHT_MOVE_MAX
    
    sm->state_id = Motor_StateId_ROOT;
}

static void RIGHT_MOVE_MAX_do(Motor* sm)
{
    // RIGHT_MOVE_MAX behavior
    // uml: do / { Motor_RIGHT_MOVE_MAX_do(sm); }
    {
        // Step 1: execute action `Motor_RIGHT_MOVE_MAX_do(sm);`
        Motor_RIGHT_MOVE_MAX_do(sm);
    } // end of behavior for RIGHT_MOVE_MAX
    
    // No ancestor handles this event.
}

static void RIGHT_MOVE_MAX_left_move(Motor* sm)
{
    // RIGHT_MOVE_MAX behavior
    // uml: LEFT_MOVE TransitionTo(LEFT_MOVE)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        RIGHT_MOVE_MAX_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `LEFT_MOVE`.
        LEFT_MOVE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for RIGHT_MOVE_MAX
    
    // No ancestor handles this event.
}

static void RIGHT_MOVE_MAX_stop(Motor* sm)
{
    // RIGHT_MOVE_MAX behavior
    // uml: STOP TransitionTo(STOP)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        RIGHT_MOVE_MAX_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `STOP`.
        STOP_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for RIGHT_MOVE_MAX
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STOP
////////////////////////////////////////////////////////////////////////////////

static void STOP_enter(Motor* sm)
{
    sm->state_id = Motor_StateId_STOP;
    
    // STOP behavior
    // uml: enter / { Motor_STOP_enter(sm); }
    {
        // Step 1: execute action `Motor_STOP_enter(sm);`
        Motor_STOP_enter(sm);
    } // end of behavior for STOP
}

static void STOP_exit(Motor* sm)
{
    // STOP behavior
    // uml: exit / { Motor_STOP_exit(sm); }
    {
        // Step 1: execute action `Motor_STOP_exit(sm);`
        Motor_STOP_exit(sm);
    } // end of behavior for STOP
    
    sm->state_id = Motor_StateId_ROOT;
}

static void STOP_do(Motor* sm)
{
    // STOP behavior
    // uml: do / { Motor_STOP_do(sm); }
    {
        // Step 1: execute action `Motor_STOP_do(sm);`
        Motor_STOP_do(sm);
    } // end of behavior for STOP
    
    // No ancestor handles this event.
}

static void STOP_left_move(Motor* sm)
{
    // STOP behavior
    // uml: LEFT_MOVE TransitionTo(LEFT_MOVE)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        STOP_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `LEFT_MOVE`.
        LEFT_MOVE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for STOP
    
    // No ancestor handles this event.
}

static void STOP_right_move(Motor* sm)
{
    // STOP behavior
    // uml: RIGHT_MOVE TransitionTo(RIGHT_MOVE)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        STOP_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `RIGHT_MOVE`.
        RIGHT_MOVE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for STOP
    
    // No ancestor handles this event.
}

// Thread safe.
char const * Motor_state_id_to_string(Motor_StateId id)
{
    switch (id)
    {
        case Motor_StateId_ROOT: return "ROOT";
        case Motor_StateId_LEFT_MOVE: return "LEFT_MOVE";
        case Motor_StateId_LEFT_MOVE_MAX: return "LEFT_MOVE_MAX";
        case Motor_StateId_RIGHT_MOVE: return "RIGHT_MOVE";
        case Motor_StateId_RIGHT_MOVE_MAX: return "RIGHT_MOVE_MAX";
        case Motor_StateId_STOP: return "STOP";
        default: return "?";
    }
}

// Thread safe.
char const * Motor_event_id_to_string(Motor_EventId id)
{
    switch (id)
    {
        case Motor_EventId_DO: return "DO";
        case Motor_EventId_LEFT_MOVE: return "LEFT_MOVE";
        case Motor_EventId_LEFT_MOVE_MAX: return "LEFT_MOVE_MAX";
        case Motor_EventId_RIGHT_MOVE: return "RIGHT_MOVE";
        case Motor_EventId_RIGHT_MOVE_MAX: return "RIGHT_MOVE_MAX";
        case Motor_EventId_STOP: return "STOP";
        default: return "?";
    }
}
