// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

    
#include "Button.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset

extern void Button_IDLE_enter(Button* sm);
extern void Button_IDLE_exit(Button* sm);
extern void Button_WAIT_enter(Button* sm);
extern void Button_WAIT_exit(Button* sm);
extern void Button_TICK_enter(Button* sm);
extern void Button_TICK_exit(Button* sm);
extern void Button_TICK_do(Button* sm);


// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(Button* sm, Button_StateId desired_state);

static void ROOT_enter(Button* sm);

static void IDLE_enter(Button* sm);

static void IDLE_exit(Button* sm);

static void IDLE_interrupted(Button* sm);

static void TICK_enter(Button* sm);

static void TICK_exit(Button* sm);

static void TICK_detected(Button* sm);

static void TICK_do(Button* sm);

static void TICK_not_detected(Button* sm);

static void WAIT_enter(Button* sm);

static void WAIT_exit(Button* sm);

static void WAIT_timeout(Button* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void Button_ctor(Button* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void Button_start(Button* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(IDLE)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `IDLE`.
            IDLE_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void Button_dispatch_event(Button* sm, Button_EventId event_id)
{
    switch (sm->state_id)
    {
        // STATE: Button
        case Button_StateId_ROOT:
            // No events handled by this state (or its ancestors).
            break;
        
        // STATE: IDLE
        case Button_StateId_IDLE:
            switch (event_id)
            {
                case Button_EventId_INTERRUPTED: IDLE_interrupted(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: TICK
        case Button_StateId_TICK:
            switch (event_id)
            {
                case Button_EventId_DO: TICK_do(sm); break;
                case Button_EventId_NOT_DETECTED: TICK_not_detected(sm); break;
                case Button_EventId_DETECTED: TICK_detected(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: WAIT
        case Button_StateId_WAIT:
            switch (event_id)
            {
                case Button_EventId_TIMEOUT: WAIT_timeout(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(Button* sm, Button_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case Button_StateId_IDLE: IDLE_exit(sm); break;
            
            case Button_StateId_TICK: TICK_exit(sm); break;
            
            case Button_StateId_WAIT: WAIT_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(Button* sm)
{
    sm->state_id = Button_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state IDLE
////////////////////////////////////////////////////////////////////////////////

static void IDLE_enter(Button* sm)
{
    sm->state_id = Button_StateId_IDLE;
    
    // IDLE behavior
    // uml: enter / { Button_IDLE_enter(sm); }
    {
        // Step 1: execute action `Button_IDLE_enter(sm);`
        Button_IDLE_enter(sm);
    } // end of behavior for IDLE
}

static void IDLE_exit(Button* sm)
{
    // IDLE behavior
    // uml: exit / { Button_IDLE_exit(sm); }
    {
        // Step 1: execute action `Button_IDLE_exit(sm);`
        Button_IDLE_exit(sm);
    } // end of behavior for IDLE
    
    sm->state_id = Button_StateId_ROOT;
}

static void IDLE_interrupted(Button* sm)
{
    // IDLE behavior
    // uml: INTERRUPTED TransitionTo(WAIT)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        IDLE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `WAIT`.
        WAIT_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for IDLE
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TICK
////////////////////////////////////////////////////////////////////////////////

static void TICK_enter(Button* sm)
{
    sm->state_id = Button_StateId_TICK;
    
    // TICK behavior
    // uml: enter / { Button_TICK_enter(sm); }
    {
        // Step 1: execute action `Button_TICK_enter(sm);`
        Button_TICK_enter(sm);
    } // end of behavior for TICK
}

static void TICK_exit(Button* sm)
{
    // TICK behavior
    // uml: exit / { Button_TICK_exit(sm); }
    {
        // Step 1: execute action `Button_TICK_exit(sm);`
        Button_TICK_exit(sm);
    } // end of behavior for TICK
    
    sm->state_id = Button_StateId_ROOT;
}

static void TICK_detected(Button* sm)
{
    // TICK behavior
    // uml: DETECTED TransitionTo(IDLE)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TICK_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `IDLE`.
        IDLE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TICK
    
    // No ancestor handles this event.
}

static void TICK_do(Button* sm)
{
    // TICK behavior
    // uml: do / { Button_TICK_do(sm); }
    {
        // Step 1: execute action `Button_TICK_do(sm);`
        Button_TICK_do(sm);
    } // end of behavior for TICK
    
    // No ancestor handles this event.
}

static void TICK_not_detected(Button* sm)
{
    // TICK behavior
    // uml: NOT_DETECTED TransitionTo(WAIT)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TICK_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `WAIT`.
        WAIT_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TICK
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state WAIT
////////////////////////////////////////////////////////////////////////////////

static void WAIT_enter(Button* sm)
{
    sm->state_id = Button_StateId_WAIT;
    
    // WAIT behavior
    // uml: enter / { Button_WAIT_enter(sm); }
    {
        // Step 1: execute action `Button_WAIT_enter(sm);`
        Button_WAIT_enter(sm);
    } // end of behavior for WAIT
}

static void WAIT_exit(Button* sm)
{
    // WAIT behavior
    // uml: exit / { Button_WAIT_exit(sm); }
    {
        // Step 1: execute action `Button_WAIT_exit(sm);`
        Button_WAIT_exit(sm);
    } // end of behavior for WAIT
    
    sm->state_id = Button_StateId_ROOT;
}

static void WAIT_timeout(Button* sm)
{
    // WAIT behavior
    // uml: TIMEOUT TransitionTo(TICK)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        WAIT_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TICK`.
        TICK_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for WAIT
    
    // No ancestor handles this event.
}

// Thread safe.
char const * Button_state_id_to_string(Button_StateId id)
{
    switch (id)
    {
        case Button_StateId_ROOT: return "ROOT";
        case Button_StateId_IDLE: return "IDLE";
        case Button_StateId_TICK: return "TICK";
        case Button_StateId_WAIT: return "WAIT";
        default: return "?";
    }
}

// Thread safe.
char const * Button_event_id_to_string(Button_EventId id)
{
    switch (id)
    {
        case Button_EventId_DETECTED: return "DETECTED";
        case Button_EventId_DO: return "DO";
        case Button_EventId_INTERRUPTED: return "INTERRUPTED";
        case Button_EventId_NOT_DETECTED: return "NOT_DETECTED";
        case Button_EventId_TIMEOUT: return "TIMEOUT";
        default: return "?";
    }
}
