// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

    
#include "CommandSender.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset

extern void CommandSender_WAIT_enter(CommandSender* sm);
extern void CommandSender_WAIT_exit(CommandSender* sm);
extern void CommandSender_TICK_enter(CommandSender* sm);
extern void CommandSender_TICK_exit(CommandSender* sm);
extern void CommandSender_TICK_do(CommandSender* sm);


// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(CommandSender* sm, CommandSender_StateId desired_state);

static void ROOT_enter(CommandSender* sm);

static void TICK_enter(CommandSender* sm);

static void TICK_exit(CommandSender* sm);

static void TICK_do(CommandSender* sm);

static void WAIT_enter(CommandSender* sm);

static void WAIT_exit(CommandSender* sm);

static void WAIT_timeout(CommandSender* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void CommandSender_ctor(CommandSender* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void CommandSender_start(CommandSender* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(WAIT)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `WAIT`.
            WAIT_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void CommandSender_dispatch_event(CommandSender* sm, CommandSender_EventId event_id)
{
    switch (sm->state_id)
    {
        // STATE: CommandSender
        case CommandSender_StateId_ROOT:
            // No events handled by this state (or its ancestors).
            break;
        
        // STATE: TICK
        case CommandSender_StateId_TICK:
            switch (event_id)
            {
                case CommandSender_EventId_DO: TICK_do(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: WAIT
        case CommandSender_StateId_WAIT:
            switch (event_id)
            {
                case CommandSender_EventId_TIMEOUT: WAIT_timeout(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(CommandSender* sm, CommandSender_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case CommandSender_StateId_TICK: TICK_exit(sm); break;
            
            case CommandSender_StateId_WAIT: WAIT_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(CommandSender* sm)
{
    sm->state_id = CommandSender_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TICK
////////////////////////////////////////////////////////////////////////////////

static void TICK_enter(CommandSender* sm)
{
    sm->state_id = CommandSender_StateId_TICK;
    
    // TICK behavior
    // uml: enter / { CommandSender_TICK_enter(sm); }
    {
        // Step 1: execute action `CommandSender_TICK_enter(sm);`
        CommandSender_TICK_enter(sm);
    } // end of behavior for TICK
}

static void TICK_exit(CommandSender* sm)
{
    // TICK behavior
    // uml: exit / { CommandSender_TICK_exit(sm); }
    {
        // Step 1: execute action `CommandSender_TICK_exit(sm);`
        CommandSender_TICK_exit(sm);
    } // end of behavior for TICK
    
    sm->state_id = CommandSender_StateId_ROOT;
}

static void TICK_do(CommandSender* sm)
{
    // TICK behavior
    // uml: do / { CommandSender_TICK_do(sm); }
    {
        // Step 1: execute action `CommandSender_TICK_do(sm);`
        CommandSender_TICK_do(sm);
    } // end of behavior for TICK
    
    // TICK behavior
    // uml: do TransitionTo(WAIT)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TICK_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `WAIT`.
        WAIT_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TICK
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state WAIT
////////////////////////////////////////////////////////////////////////////////

static void WAIT_enter(CommandSender* sm)
{
    sm->state_id = CommandSender_StateId_WAIT;
    
    // WAIT behavior
    // uml: enter / { CommandSender_WAIT_enter(sm); }
    {
        // Step 1: execute action `CommandSender_WAIT_enter(sm);`
        CommandSender_WAIT_enter(sm);
    } // end of behavior for WAIT
}

static void WAIT_exit(CommandSender* sm)
{
    // WAIT behavior
    // uml: exit / { CommandSender_WAIT_exit(sm); }
    {
        // Step 1: execute action `CommandSender_WAIT_exit(sm);`
        CommandSender_WAIT_exit(sm);
    } // end of behavior for WAIT
    
    sm->state_id = CommandSender_StateId_ROOT;
}

static void WAIT_timeout(CommandSender* sm)
{
    // WAIT behavior
    // uml: TIMEOUT TransitionTo(TICK)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        WAIT_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TICK`.
        TICK_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for WAIT
    
    // No ancestor handles this event.
}

// Thread safe.
char const * CommandSender_state_id_to_string(CommandSender_StateId id)
{
    switch (id)
    {
        case CommandSender_StateId_ROOT: return "ROOT";
        case CommandSender_StateId_TICK: return "TICK";
        case CommandSender_StateId_WAIT: return "WAIT";
        default: return "?";
    }
}

// Thread safe.
char const * CommandSender_event_id_to_string(CommandSender_EventId id)
{
    switch (id)
    {
        case CommandSender_EventId_DO: return "DO";
        case CommandSender_EventId_TIMEOUT: return "TIMEOUT";
        default: return "?";
    }
}
